export function populateUsers() {
  // This function populates the users data
  const dummyUsers = [
    {
      id: 1,
      firstName: "Shantanu",
      lastName: "Goel",
      email: "shantanu.goel-dev-2@cloudkeeper.com",
      roles: ["Admin", "Login-ReadOnly", "LoginRole"],
      lastLogin: "13/11/2025 23:55",
      active: true,
      canPromote: true,
      canResend: false,
    },
    {
      id: 2,
      firstName: "Rohit",
      lastName: "Pant",
      email: "rohit.pant-dev2new@cloudkeeper.com",
      roles: ["Admin"],
      lastLogin: "29/09/2025 15:04",
      active: true,
      canPromote: true,
      canResend: false,
    },
    {
      id: 3,
      firstName: "Vikram",
      lastName: "Mandal",
      email: "vikram.mandal@cloudkeeper.com",
      roles: ["Tuner-test-perm"],
      lastLogin: "",
      active: false,
      canPromote: true,
      canResend: true,
    },
    {
      id: 4,
      firstName: "Sneha",
      lastName: "Patel",
      email: "sneha.patel@example.com",
      roles: ["customer", "admin"],
      lastLogin: "11/20/2025, 1:53:00 PM",
      active: true,
      canPromote: true,
      canResend: false,
    },
    {
      id: 5,
      firstName: "Aisha",
      lastName: "Khan",
      email: "aisha.khan@example.com",
      roles: ["User"],
      lastLogin: "2025-10-02 09:12",
      active: true,
      canPromote: false,
      canResend: false,
    },
    {
      id: 6,
      firstName: "Diego",
      lastName: "Martinez",
      email: "diego.martinez@example.com",
      roles: ["Editor", "Login-ReadOnly"],
      lastLogin: "05/12/2025, 08:30:00 AM",
      active: true,
      canPromote: true,
      canResend: false,
    },
    {
      id: 7,
      firstName: "Lena",
      lastName: "Schmidt",
      email: "lena.schmidt@example.com",
      roles: ["Viewer"],
      lastLogin: "",
      active: false,
      canPromote: false,
      canResend: true,
    },
    {
      id: 8,
      firstName: "Omar",
      lastName: "Farouk",
      email: "omar.farouk@example.com",
      roles: ["Support", "LoginRole"],
      lastLogin: "2025-09-18T14:22:00Z",
      active: true,
      canPromote: true,
      canResend: false,
    },
    {
      id: 9,
      firstName: "Priya",
      lastName: "Iyer",
      email: "priya.iyer@example.com",
      roles: ["Billing"],
      lastLogin: "22/11/2025 11:05",
      active: true,
      canPromote: false,
      canResend: false,
    },
    {
      id: 10,
      firstName: "Tom",
      lastName: "O'Connor",
      email: "tom.oconnor@example.com",
      roles: ["Admin", "Editor"],
      lastLogin: "2025-07-30 19:45",
      active: true,
      canPromote: true,
      canResend: false,
    },
    {
      id: 11,
      firstName: "Yuki",
      lastName: "Tanaka",
      email: "yuki.tanaka@example.com",
      roles: ["Tuner-test-perm"],
      lastLogin: "",
      active: false,
      canPromote: true,
      canResend: true,
    },
    {
      id: 12,
      firstName: "Marcus",
      lastName: "Lee",
      email: "marcus.lee@example.com",
      roles: ["User", "Login-ReadOnly"],
      lastLogin: "09/10/2025 07:10",
      active: true,
      canPromote: false,
      canResend: false,
    },
    {
      id: 13,
      firstName: "Elena",
      lastName: "Garcia",
      email: "elena.garcia@example.com",
      roles: ["Viewer", "Support"],
      lastLogin: "2025-11-01T12:00:00Z",
      active: true,
      canPromote: false,
      canResend: false,
    },
    {
      id: 14,
      firstName: "Noah",
      lastName: "Brown",
      email: "noah.brown@example.com",
      roles: ["Admin"],
      lastLogin: "03/03/2025 16:20",
      active: false,
      canPromote: true,
      canResend: true,
    },
    {
      id: 15,
      firstName: "Zara",
      lastName: "Ali",
      email: "zara.ali@example.com",
      roles: ["Editor"],
      lastLogin: "2025-11-18 21:40",
      active: true,
      canPromote: false,
      canResend: false,
    },
    {
      id: 16,
      firstName: "Ethan",
      lastName: "Wong",
      email: "ethan.wong@example.com",
      roles: ["User"],
      lastLogin: "",
      active: false,
      canPromote: false,
      canResend: true,
    },
    {
      id: 17,
      firstName: "Maya",
      lastName: "Rao",
      email: "maya.rao@example.com",
      roles: ["LoginRole", "Viewer"],
      lastLogin: "10/11/2025, 02:15:00 PM",
      active: true,
      canPromote: true,
      canResend: false,
    },
    {
      id: 18,
      firstName: "Luca",
      lastName: "Bianchi",
      email: "luca.bianchi@example.com",
      roles: ["Support"],
      lastLogin: "2025-08-25 05:55",
      active: true,
      canPromote: false,
      canResend: false,
    },
    {
      id: 19,
      firstName: "Sara",
      lastName: "Nordin",
      email: "sara.nordin@example.com",
      roles: ["Billing", "Viewer"],
      lastLogin: "12/12/2025 10:00",
      active: true,
      canPromote: false,
      canResend: false,
    },
    {
      id: 20,
      firstName: "Jacob",
      lastName: "Ng",
      email: "jacob.ng@example.com",
      roles: ["Admin", "Login-ReadOnly"],
      lastLogin: "2025-11-20T23:00:00Z",
      active: true,
      canPromote: true,
      canResend: false,
    },
    {
      id: 21,
      firstName: "Amira",
      lastName: "Hassan",
      email: "amira.hassan@example.com",
      roles: ["User", "Support"],
      lastLogin: "",
      active: false,
      canPromote: false,
      canResend: true,
    },
    {
      id: 22,
      firstName: "Carlos",
      lastName: "Santos",
      email: "carlos.santos@example.com",
      roles: ["Editor", "Viewer"],
      lastLogin: "2025-06-14 14:14",
      active: true,
      canPromote: false,
      canResend: false,
    },
    {
      id: 23,
      firstName: "Ivy",
      lastName: "Chen",
      email: "ivy.chen@example.com",
      roles: ["Tuner-test-perm", "User"],
      lastLogin: "01/11/2025 09:09",
      active: true,
      canPromote: true,
      canResend: false,
    },
    {
      id: 24,
      firstName: "Ben",
      lastName: "Walker",
      email: "ben.walker@example.com",
      roles: ["Viewer"],
      lastLogin: "",
      active: false,
      canPromote: false,
      canResend: true,
    },
    {
      id: 25,
      firstName: "Nadia",
      lastName: "Popov",
      email: "nadia.popov@example.com",
      roles: ["Admin", "Billing"],
      lastLogin: "2025-10-31 18:30",
      active: true,
      canPromote: true,
      canResend: false,
    },
    {
      id: 26,
      firstName: "Hassan",
      lastName: "Qureshi",
      email: "hassan.qureshi@example.com",
      roles: ["Support", "LoginRole"],
      lastLogin: "14/09/2025 07:45",
      active: true,
      canPromote: false,
      canResend: false,
    },
    {
      id: 27,
      firstName: "Grace",
      lastName: "Kim",
      email: "grace.kim@example.com",
      roles: ["Editor"],
      lastLogin: "2025-11-19T06:30:00Z",
      active: true,
      canPromote: false,
      canResend: false,
    },
    {
      id: 28,
      firstName: "Pavel",
      lastName: "Ivanov",
      email: "pavel.ivanov@example.com",
      roles: ["User"],
      lastLogin: "",
      active: false,
      canPromote: false,
      canResend: true,
    },
    {
      id: 29,
      firstName: "Olivia",
      lastName: "Johnson",
      email: "olivia.johnson@example.com",
      roles: ["Admin", "Editor"],
      lastLogin: "07/07/2025 12:00",
      active: true,
      canPromote: true,
      canResend: false,
    },
    {
      id: 30,
      firstName: "Kenji",
      lastName: "Sato",
      email: "kenji.sato@example.com",
      roles: ["Viewer", "Login-ReadOnly"],
      lastLogin: "2025-11-15 03:20",
      active: true,
      canPromote: false,
      canResend: false,
    },
    {
      id: 31,
      firstName: "Rina",
      lastName: "Das",
      email: "rina.das@example.com",
      roles: ["Tuner-test-perm"],
      lastLogin: "",
      active: false,
      canPromote: true,
      canResend: true,
    },
    {
      id: 32,
      firstName: "Liam",
      lastName: "Murphy",
      email: "liam.murphy@example.com",
      roles: ["Support"],
      lastLogin: "2025-05-21 20:10",
      active: true,
      canPromote: false,
      canResend: false,
    },
    {
      id: 33,
      firstName: "Sofia",
      lastName: "Rossi",
      email: "sofia.rossi@example.com",
      roles: ["Billing", "User"],
      lastLogin: "11/11/2025 11:11",
      active: true,
      canPromote: false,
      canResend: false,
    },
    {
      id: 34,
      firstName: "Victor",
      lastName: "Petrov",
      email: "victor.petrov@example.com",
      roles: ["Admin"],
      lastLogin: "2025-04-04 04:04",
      active: false,
      canPromote: true,
      canResend: true,
    }

  ];
  return dummyUsers;
}
